version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: always
    hostname: netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - //:/host:ro

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: always
    ports:
      - 8428:8428

  vmagent:
    image: victoriametrics/vmagent
    container_name: vmagent
    restart: always
    ports:
      - 8429:8429
    volumes:
      - ./vmagent/vmagent.yaml:/etc/vmagent.yaml
    command: [
      '-promscrape.config=/etc/vmagent.yaml',
      '-remoteWrite.url=http://victoriametrics:8428/api/v1/write'
    ]

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - victoriametrics
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage:
